### PR TITLE
2.1 text transcripts dao

### PR DESCRIPTION
**Pull request by Ajinkya-B**
**Implementation**

### Summary of Changes

- Separated the DAO into two files. One for transcripts and the other for text transcripts.
- Created a helper method in trascriptDataFormatter for formatting text transcripts.
- Changed the routes for text transcripts

### Related PRs

- https://github.com/Ajinkya-B/Ghost-Busters/issues/1

### CODE REVIEW

**Comment by ProEdge2** [comment]
Do you think it would be beneficial for me to condense the function in transcriptDataFormetter?

**Comment by ProEdge2** [comment]
I also think the in the front end under the UploadTranscripts file the postData method should be posting the axios call instead of getting it

**Comment by Ajinkya-B** [comment]
> Do you think it would be beneficial for me to condense the function in transcriptDataFormetter?

Yup, that would be great! Just make sure to add any comments wherever necessary.

**Comment by ProEdge2** [comment]
These changes look great Ajinkya, I have reviewed the code and will submit the pull request right now!

**Review by ProEdge2 — APPROVED** [review]
All these changes look great!

**Pull request merged**
